### ISSUE TITLE
Typescript handlers

### ISSUE THREAD

**Issue by darbio** [mj1618/serverless-offline-sns-example#1]
I'm using your plugin to simulate SNS locally for my serverless project.

My handlers are written in typescript, and I am using serverless-plugin-typescript. When I send a payload to a topic, the handler cannot be found (typescript is complied to another folder - `.build`) and the handler therefore doesn't run.

Is there a way to make this plugin work with typescript?

**Comment by mj1618** [comment]
Hey @darbio !

Thanks for the bug report. Yea it’s clearly not looking in the right folder.

With the web pack plugin it requires that it is listed first in the plugin list. That way serverless offline picks it up.

Does serverless typescript have the same requirement? Are you using serverless offline?

**Comment by darbio** [comment]
Cheers @mj1618. Yes I'm using serverless-offline and I played with the order to see if I could get it to work but no luck. 

As a quick fix I added '.build' to the require path in one of the files which referenced the transpiled output. I'll check which one tomorrow, but that directory is where serverless-typescript builds to. 

I had a look at the serverless-typescript plugin but it wasn't immediately obvious how it works and I ran out of time. 

I'll throw together an example so we can find a way to make it work.

**Comment by mj1618** [comment]
Thanks man no problem. I will probably have a play this weekend and get it working

**Comment by darbio** [comment]
This is my serverless.yml (boiled down to 2 functions):

```
service: serverless-api
provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'local'}
  region: us-east-1
functions:
  api-status:
    handler: functions/api/status/handler.index
    events:
      - http:
          path: status
          method: get
          cors: true
  wp-event-sink:
    handler: functions/workers/shared/event-sink/handler.index
    events:
      - sns: ${self:custom.sns-topic-website-submit-survey}
      - sns: ${self:custom.sns-topic-shared-email}
plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline-sns
  - serverless-offline
```
Adding `/.build` on dist/index.js:197 fixed the issue temporarily for me, as serverless-plugin-typescript compiles to the `/.build` dir:

```
var handler = require(process.cwd() + "/.build/" + fn.handler.split(".")[0])[fn.handler.split("/").pop().split(".")[1]];
```

I haven't had a chance to look at the way that serverless-plugin-typescript does things yet (I had a quick look - but it's not obvious). They do some symlinking and some file moving in their code, which might be the answer? I haven't had the time to work out exactly how they point handlers to the js yet...

Also, I realise that maybe I put this in the wrong repository. If you want to move it to the [project repo](https://github.com/mj1618/serverless-offline-sns) feel free!

If you do find a way to do it and need someone to implement, let me know and I'll happily PR.
